### PR TITLE
Address fake news and related problems

### PR DESCRIPTION
**Pull request by LuxLang**

### CODE REVIEW

**Comment by chrisjensen** [comment]
This would need to be more specifically defined and risks over-reach.
All news outlets have had to issue corrections at one time or another, so they have all technically spread misinformation at one time or another.

**Comment by Archcry** [comment]
There is even a website in the Netherlands that spreads misinformation by design in a satirical way. It's a amusing website and it is clear that the information is not true. Doing this would disallow them to use software under this license.

**Comment by tommaitland** [comment]
The measure could be **deception** – maybe something like `information designed to deceive` which would allow for satire?

**Comment by chrisjensen** [comment]
Anyone want to create a PR for this?

I think there's still some blurriness here. There is some satire that really would push the limits of this, but I guess thats what courts are for.

**Comment by chrisjensen** [comment]
Oh, sorry, I thought this was an issue, not a PR. I can update the PR

**Comment by chrisjensen** [comment]
This language looks good, thanks Tom.

It just occurred to me that this excludes the use of the software for pranks and April fools jokes.
While this isn't the end of the world, it does make me wonder if there are other unintended consequences we haven't considered.

I might leave this open for a few more days to keep thinking.

**Comment by tommaitland** [comment]
True – the other term we could use is *propaganda* to cover this? Or limit this to cover politics/power:

`creation or distribution of information intended to interfere with the democratic process`

Or even more broadly just adding `democracy` to 4.b.

I think it's fair that most of our issues with fake news are really attempts to *frustrate democracy*. Might be reasonable coverage that doesn't have unintended side effects?

**Comment by chrisjensen** [comment]
And I think anything that isn't frustrating democracy would frustrate one of the others.

Could we call it _democratic processes_?

Democracy is [defined](https://www.merriam-webster.com/dictionary/democracy) as a specific system of government, but:

1) If someone were to, say, use propaganda to undermine the fairness of a Parents and Teachers association council decision, we'd probably still want to exclude that even though it's not a system of government.

2) There are other forms of government and I don't think it's a done deal that they're all bad. eg The Kingdom of Bhutan, (its far from a perfect example, but so are the US and Australia right now ;-) )  Presumably the license would also be against propaganda designed to create civil unrest or unseat the king too.

_democratic processes_ covers (a), not sure about (b), but it at least doesn't presume that democracy is the be all and end all of governing.

**Comment by LuxLang** [comment]
> Or limit this to cover politics/power

You can also get plenty of propaganda that isn't necessarily politics-related.

For example:
* Make girls very self-aware about their appearance in order to push make-up on them.
* Make people feel peer-pressure to smoke through advertisement.
* Convince unsuccessful males that using a special brand of deodorant or perfume will attract women.
* Convince people a new virtual currency is the future in order to boost financial speculation and cash-in on people's gullibility (the tech and financial sectors are really suffering this one nowadays).

You can get plenty of less-than-honest propaganda just from a profit motive alone, without trying to subvert democracy or any other kind of political system.

**Pull request merged**
