### PR TITLE
~~~

### PR DESCRIPTION
**Pull request by katyannflowergirl**
sex trafficking and human trafficking are redundant and basically the same as slavery or forced labor. Also Porn as a category is too ambiguous and could come off as anti sex-worker. Many sex workers publish their own videos + cooperatively run cam-sites. Added policing and prisons to be more specific
Love and solidarity,
ACAB 
FTTP
-I.W.W. Mid Atlantic General Defense Committee

### CODE REVIEW

**Comment by chrisjensen** [comment]
Thanks for the pull request.
Pornography has already been removed.
My understanding of Sex/Human trafficking is that it is the act of transporting/selling people for the purposes of forced labor, so it might be good to keep them in there.

**Comment by chrisjensen** [comment]
Coming back to this after a long hiatus. Apologies, I seem to have missed the part about policing & prisons previously and was also unclear in my response on trafficking.

I think the point i was trying to make on trafficking was that _i think_ the act of trafficking itself can potentially be separate from slavery or forced labor and therefore is worth retaining. If it is redundant do you see any harm in it being there?

On policing and prisons, since initially drafting the license, I've come a long way personally in my understanding of prisons and policing and alternatives. However, at the time of authoring, we were careful about the wording because the aim was to exclude usage by the military, but to permit usage by peaceful policing that is in the public interest. If I were to write the license again today I might come to a different conclusion, but in the interests of keeping with the same spirit that other contributors joined in the first place, I'm inclined to not explicitly deny policing.

**Comment by chrisjensen** [comment]
That said, I'd welcome other views on this.

**Comment by tommaitland** [comment]
Closing – stale.

**Pull request closed without merging**
