### PR TITLE
Deforestation

### PR DESCRIPTION
**Pull request by chrisjensen**
@tommaitland I had some thoughts this afternoon so penned them.
Wasn't able to do it without a definition, but it's a short definition that I think covers:

Allows
* Farming
* Sustainable forestry

Disallows
* Slash and burn
* What we would generally consider deforestation

### CODE REVIEW

**Comment by Knagis** [comment]
the definition should at least include that the 0.5ha should be one continuous area (sector). Otherwise any large scale forest service will not qualify no matter how responsible because if you own 1000ha, you will definitely cut down more than 0.5ha every year.
Alternatively exclude cases when forest is being planted right away in place of the cut trees.

**Comment by tommaitland** [comment]
@Knagis That's a good point – can you propose a PR?

**Comment by Knagis** [comment]
Sorry, I will not be suited for writing legal wording for this...

**Comment by gargantuan** [comment]
Can I suggest that sustainable forestry, — as defined by the Ministerial Conference on the protection of forrests in Europe, and adopted by the UN FAO — be permitted? 

> The stewardship and use of forests and forest lands in a way, and at a rate, that maintains their biodiversity, productivity, regeneration capacity, vitality and their potential to fulfill, now and in the future, relevant ecological, economic and social functions, at local, national, and global levels, and that does not cause damage to other ecosystems.

https://en.m.wikipedia.org/wiki/Sustainable_forest_management

I fear the current terms relating to forrestry and deforestation might be too simplistic, to the detriment of good actors.

By deferring to an officially recognised definition of sustainable forresty, the licence can succinctly capture a complex issue, and bolster the efforts of the UN/FAO.

**Pull request merged**
