### PR TITLE
[stale] Add licence summary

### LINKED ISSUE #72: Add a summary?
For all the people casually checking out the licence a short summary would be quite helpful including a basic list of the licence's rules.

### PR DESCRIPTION
**Pull request by realpixelcode**
Adds an easy-to-understand summary of the licence. Fixes #72.

### CODE REVIEW

**Comment by ghost** [comment]
Just read it. Very concise and digestible. Now I bet the core team is going to probably ask on how to integrate it into the main license for ease of access, or probably include a reference in the README.md.

**Comment by realpixelcode** [comment]
> Just read it. Very concise and digestible. Now I bet the core team is going to probably ask on how to integrate it into the main license for ease of access, or probably include a reference in the README.md.

Just added a link to the README.md :)

**Comment by ghost** [comment]
@realpixelcode, I was just rereading your license summary, and I was thinking that if this PR gets merged before mine (#79), I think I could *possibly* make a template for the summary as well (I would have to ask the core team because it would require different API). What do you think?

**Comment by realpixelcode** [comment]
In principle, I find that a good idea, I'm just wondering how you would do that? A script would most likely not be sufficiently "intelligent" enough to generate a summary out of a new licence text itself.

**Comment by ghost** [comment]
I mean to modify the existing context to build the summary from its own template. This is much more simpler than machine learning.

**Comment by realpixelcode** [comment]
Ok, go ahead then, I guess 😊

**Comment by ghost** [comment]
Sorry for the late response. I thought I responded earlier.

**Comment by ghost** [comment]
*(edited for grammar)*

Still waiting for review from the core team. They may not want to "template-ify" the summary.

**Comment by realpixelcode** [comment]
> Sorry for the late response. I thought I responded earlier.

No worries, mate :) Aren't we multiple time zones apart anyway? 😄 Also, others take much longer. 🤷

**Comment by ghost** [comment]
Hello @realpixelcode. I can see that this PR is not getting merged; the same is happening for me, so I decided to prefix the title my PR (#79 ) with `[Stale!]`, and I'm thinking about closing it entirely and keeping the branch for when someone wants to re-open it.

**Review by tommaitland — APPROVED** [review]
Sorry for the delay here, thanks for the contribution!

**Comment by realpixelcode** [comment]
> Sorry for the delay here, thanks for the contribution!

No worries :)

**Pull request merged**
