### PR TITLE
Freedom of workers to organize?

### PR DESCRIPTION
**Pull request by ghost**
The license wants to avoid having the code be used by those who wish to frustrate the _freedom of workers to unionise_.

It would be more general to say the _freedom of workers to organize_.

It may sound like splitting hairs, but some workers may choose to go with a federative or an anarcho-syndicalist model, instead of a union; which is also a valid form of organization that employers may want to suppress as much as a union.

### CODE REVIEW

**Comment by chrisjensen** [comment]
Good point. I'll look at merging this on return.

**Comment by chrisjensen** [comment]
Question though: The definition of unionize is fairly well understood and would generally stand on it's own. Is the "freedom to organise" as well understood outside the circles of community/union organisers?

**Comment by chrisjensen** [comment]
To be clear, I think it's a good point, just not sure of the wording.

The word organize may be interpreted outside the context of political or labor organizing.

A (contrived) example: Developers at a company want to organize a bake sale in support of a children's charity on a Thursday. The owners of the company know that there is an important release scheduled on Friday and are concerned that they need all hands on deck to meet it and insist that the staff change the date of the bake sale.

A literal reading of "freedom to organize" would put the company in breech of the license conditions, even though that is not the intention of that condition.

**Comment by LuxLang** [comment]
How about, instead of the phrases:

> freedom of workers to organize

and

> freedom of workers to unionise

How about the phrase:

> worker associations

Then, in full context:

> b) lobbies against, or derives a majority of income from actions that discourage or frustrate: peace, universal access to human rights, worker associations, a safe environment, or action to curtail the use of fossil fuels or prevent climate change.

**Comment by tommaitland** [comment]
The Universal Declaration touches on this, I wonder if we should broaden it beyond workers? Article 20.1 is:

> 1. Everyone has the right to freedom of peaceful assembly and association.

Taking that definition the clause could be:

> b) lobbies against, or derives a majority of income from actions that discourage or frustrate: peace, universal access to human rights, *peaceful assembly and association*, a safe environment, or action to curtail the use of fossil fuels or prevent climate change.

The thought being that actually anyone should be able to organise, not just workers?

**Comment by LuxLang** [comment]
I think there's value in being specific about workers, given how hostile many companies are to them organizing.

Proposed middle-ground:

> peaceful assembly and association (including worker associations)

**Comment by chrisjensen** [comment]
I'm good with this.

**Comment by LuxLang** [comment]
@chrisjensen Updated the PR.

**Pull request merged**
