### PR TITLE
added awareness of doxing and blackmaling

### PR DESCRIPTION
**Pull request by eylles**
## Overview
1) for a true ethical software the modern concerns of doxxing, targeted harassment, threatening and blackmailing should be taken on account.

2) the current state of the license only recognizes organizations, websites, products and services but leaves out individuals.

## Proposed Resolution
1) adding awareness of the issues of doxing, blackmailing, targeted harassment and threatening to the license.

2) adding awareness about individuals.

### CODE REVIEW

**Comment by aeriksen** [comment]
I like it. I do however not see a problem with nuclear energy. I suggest reading up on the subject.
The Norwegian Green Party (Med de Grønne/MdG) is the only party that I’m aware of in our parliament that is for nuclear energy, there are good scientific, economic and ecological reasons for this.


Best regards
Arnkjell Eriksen

**Comment by eylles** [comment]
@aeriksen the nuclear power clause is part of the original license, i didn't add that, but i would like to suggest it's removal in a future PR, i being an electronics engineering student myself i think that nuclear power is the way to go in the areas where geothermal power ain't viable, prefferably with thorium reactors.

**Comment by eylles** [comment]
@chrisjensen

**Comment by ghost** [comment]
> @aeriksen the nuclear power clause is part of the original license, i didn't add that, but i would like to suggest it's removal in a future PR, i being an electronics engineering student myself i think that nuclear power is the way to go in the areas where geothermal power ain't viable, prefferably with thorium reactors.

@eylles is correct. I just checked the commit, and the diffs do not show any additions about nuclear energy. @tommaitland, what do you think of this PR? If you like it sir, then I can incorporate it into #79.

**Comment by ghost** [comment]
@eylles you may want to pull from upstream to resolve the merge conflicts :) Section 5 had a lot of changes since the last commit on this PR.

### Edit 16 September, 2022

~~You may want to clarify a few things:~~ Everything is good

**Comment by eylles** [comment]
sorry, i've been busy with some projects, is there something needed in order to proceed here?

**Comment by ghost** [comment]
*(edited for grammar errors)*
@eylles, let me look at your commits and compare them to PR #76 because *I think* that PR may be on its way to getting merged with changes that are similar to yours. Also, you're going to have a (possibly) worse merge conflict because your fork is 30 commits behind `raisely:publish`, so I would not recommend making any changes yet until I come back with more info. :)

**Comment by ghost** [comment]
@eylles, I am sorry to say that you are going to have very, very ugly merge conflicts; the `LICENSE.md` file has changed drastically since you forked the repository. If I were you, I would pull upstream from `raisely:publish` to `eylles:publish`, and then try to merge to `eylles:no-dox-harass-blackmail` from there; If these changes from `eylles:publish` to `eylles:no-dox-harass-blackmail` are too ugly to resolve, you may to need to start from a clean slate, wait for #76 to merge (or close), pull from upstream, and re-create a new PR. I wish I could fork from your fork and help you out, but I already have a fork from @raisely.

**Comment by tommaitland** [comment]
I believe doxing and blackmailing are adequately covered by [Article 12 of the UDHR](https://github.com/raisely/NoHarm/blob/publish/documents/UDHR.md#article-12) or covered by criminal codes and we don't need these called out specifically in the license.

I'm going to close the PR because @IRod22 likes things tidy (😉) but happy to discuss in an issue first if anyone feels this is the wrong approach.

**Comment by ghost** [comment]
@eylles, I would still pull from upstream that way you can contribute in the future.

**Pull request closed without merging**
